name: Docker Build and K8s Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run SonarQube Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          sonar-scanner \
            -Dsonar.projectKey=myapp \
            -Dsonar.sources=. \
            -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}

      - name: Set up Docker Buildx
        run: sudo docker build -t myimage .

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKER_TOKEN }}" | sudo docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Tag Docker image
        run: sudo docker tag myimage:latest ${{ secrets.DOCKER_USERNAME }}/myimage:latest

      - name: Scan the image
        run: sudo trivy image ${{ secrets.DOCKER_USERNAME }}/myimage:latest

      - name: Push Docker image
        run: sudo docker push ${{ secrets.DOCKER_USERNAME }}/myimage:latest

      - name: Deploy to kubernetes
        run: sudo kubectl apply -f Deployment.yaml

      - name: Restart deployment
        run: sudo kubectl rollout restart deployment myapp || true

      - name: Expose to browser
        run: sudo kubectl apply -f Service.yaml